#!/bin/sh
#
# This example shows how to configure afio to unpack GnuPG encrypted archives.
# it is a companion script to afio_pack_gpg_zip, see the comments there.

passphrasefile=my_passphrasefile

afio -ivzZ -3 3 -P ./gpg_decrypt_unzip my_archive_file 3<my_passphrasefile


