#!/bin/sh
#
# This example shows how to configure afio to write GnuPG encrypted archives.

# What is GnuPG?

# 	OVERVIEW  

# GnuPG is a complete and free replacement for PGP. Because it does not use
# IDEA or RSA it can be used without any restrictions. GnuPG is a RFC2440
# (OpenPGP) compliant application.

# 	(Some)  Features 

# 	*     Full replacement of PGP. 
# 	*     Does not use any patented algorithms. (!!!!!!!!!!!!!!!!)
# 	*     GPLed, written from scratch. 
# 	*     Can be used as a filter program. 
# 	*     Full OpenPGP implementation. 
# 	*     Better functionality than PGP and some security enhancements. 
# 	*     Decrypts and verifies PGP 5.x messages. 


# Where can I get GnuPG ?

# 	http://www.gnupg.org/  




# How can I use GnuPG to encrypt my archives ?
# 

# If you are using bash, you can use the input redirection by opening a second
# input stream linked to a file containing your pass phrase. Be careful about
# that file's permissions!
#
# only working with bash(?):
#
find *|afio -ovz -Z -U -P gpg -Q --symmetric \
	     -Q --passphrase-fd=3 -Q --no-verbose \
	     -Q --batch -Q --no-options -3 3 \
             my_archive_file \
		3<my_passphrasefile

